Intermediate refactoring #2
securedevteam/Security-Database-Sync pull request #10
Opened 2021-05-14 23:21 UTC by MikhailMasny

Intermediate refactoring of the application to improve performance.

2021-05-19 08:15 UTC, s207883 requested changes

2021-05-19 08:15 UTC, s207883 commented on src/Secure.SecurityDatabaseSync.Seed/Program.cs
> -            catch (Exception ex)
Cath отлавливает все исключения, при том, что в явном виде ты выбрасываешь только ArgumentException. Лучше разделить на ошибки на ожидаемые и нет.

2021-05-19 08:15 UTC, s207883 commented on src/Secure.SecurityDatabaseSync.UI/Program.cs
> -                                ISyncService defaultSyncService = new DefaultSyncService(sourceDb, targetDb, code);
Вынеси объявление  и вызов IAsyncTask за пределы switch (до и после тела switch соответственно). Объявление и вызов одного и того же выглядит избыточно..

2021-05-19 08:15 UTC, s207883 commented on src/Secure.SecurityDatabaseSync.DAL/Extensions/ApplicationContextExtension.cs
> +                new ApplicationContext(
Добавить проверку значений. Проверку существования appSettings в принципе и наличия в нем строки подключения с параметром.

2021-05-19 08:15 UTC, s207883 commented on src/Secure.SecurityDatabaseSync.DAL/Contexts/ApplicationContext.cs
> +        /// Contructor with params.
Было без опечатки, стало с.

2021-05-19 08:15 UTC, s207883 commented on src/Secure.SecurityDatabaseSync.BLL/Tasks/BulkSyncTask.cs
> +                    if (targetModel.Name != sourceModel.Name)
sourceModel может быть default, нужна проверка или замена FirstOrDefault на First.

2021-05-19 08:15 UTC, s207883 commented on src/Secure.SecurityDatabaseSync.BLL/Tasks/DefaultSyncTask.cs
> +                    if (common is not null)
Если common is null, то обновление вроде как не имеет смысла?

2021-05-19 19:15 UTC, MikhailMasny commented on src/Secure.SecurityDatabaseSync.Seed/Program.cs
> -            catch (Exception ex)
Исправлено

2021-05-19 19:15 UTC, MikhailMasny commented on src/Secure.SecurityDatabaseSync.UI/Program.cs
> -                                ISyncService defaultSyncService = new DefaultSyncService(sourceDb, targetDb, code);
Исправлено

2021-05-19 19:15 UTC, MikhailMasny commented on src/Secure.SecurityDatabaseSync.DAL/Extensions/ApplicationContextExtension.cs
> +                new ApplicationContext(
Исправлено

2021-05-19 19:15 UTC, MikhailMasny commented on src/Secure.SecurityDatabaseSync.BLL/Tasks/BulkSyncTask.cs
> +                    if (targetModel.Name != sourceModel.Name)
Исправлено

2021-05-19 19:15 UTC, MikhailMasny commented on src/Secure.SecurityDatabaseSync.BLL/Tasks/DefaultSyncTask.cs
> +                    if (common is not null)
Исправлено

2021-05-24 10:37 UTC, s207883 approved these changes

2021-05-24 17:13 UTC, merged